version: 2

project_name: tk

before:
  hooks:
    - go mod tidy

builds:
  - id: tk
    main: ./cmd/tk
    binary: tk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: radutopala
    name: ticket
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: tk
    repository:
      owner: radutopala
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/radutopala/ticket
    description: Minimal CLI ticket management system for AI agents
    license: MIT
    commit_author:
      name: Radu Topala
      email: radu.topala@trisoft.ro
    install: |
      bin.install "tk"
    test: |
      system "#{bin}/tk", "--help"
